[env]
PROJECT_NAME = "kilo4"
DOMAIN_NAME = "kilo4.com"
AMI_SSM_PARAMETER = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64"
EMAIL_ADDRESS = ""

[tools]
jq = "latest"
python = "3.14.2"
shellcheck = "latest"
